
version: "3.3"

services:
  # CONFIG DEPLOY SERVICE TO WEB CLIENT
  client:
    build:
      context: ./deploy/
      dockerfile: client.dockerfile
    command: bash -c "npm install && npm start" 
    container_name: client_fcm_integration
    ports:
    - 1324:1324
    volumes:
      - ./src/client:/fcm_integration/client

  # CONFIG DEPLOY SERVICE TO API
  api:
    build:
      context: ./deploy/
      dockerfile: api.dockerfile
    command: bash -c "chmod +x /go/src/fcm_integration/watch_server && /go/src/fcm_integration/watch_server"
    container_name: api_fcm_integration
    ports:
    - 1323:1323
    volumes:
      - ./src/api:/go/src/fcm_integration/

  # CONFIG DEPLOY SERVICE POSTGRESQL
  postgres:
    image: postgres:9.6.4
    restart: always
    container_name: postgres_fcm_integration
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: fcm_integration
      POSTGRES_PASSWORD: fcm_integration
      POSTGRES_USER: fcm_integration